# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: foo="Endpoint=https://tfjnhyllghvwu.service.signalr.net;AccessKey=qx7MliZtP5mEGHhwya1xl8RzjrgjmQr8savv4B9ljfc=;Version=1.0;"
- script: dotnet user-secrets set Azure:SignalR:ConnectionString $(foo)
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
